eureka:
  instance:
    hostname: subject-service
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
server:
  port: 8096
spring:
  application:
    name: subjects

  config:
    import: optional:configserver:http://config-server:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/subject
    hikari:
      username: school
      password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  spring:
    zipkin:
      enabled: false

application:
  config:
    teachers-url: http://teacher-service:8092/api/v1/teachers
