eureka:
  client:
    register-with-eureka: false
server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/students/**

        - id: students
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/parentActivity/**

        - id: parents
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/parents/**

        - id: parents
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/family/**

        - id: activite
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/activity/**

        - id: activite
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/activity/class/**

        - id: activite
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/calendar/**

        - id: dalyReport
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/daly/**

        - id: dalyReport
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/evaluation/**

        - id: teachers
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/teachers/**

        - id: events
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/event/**

        - id: token
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/register/**

        - id: token
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/authenticate/**

        - id: token
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/refresh-token/**

        - id: payment
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/payment/**

        - id: chat
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/chatRooms/**

        - id: chat
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/messages/**

        - id: chat
          uri: http://localhost:8091
          predicates:
            - Path=/**